# Generated by Django 3.2.5 on 2021-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specfile'),
        ),
    ]
